apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: h34qtufqb-nodejs 
  janus-idp.io/tekton: h34qtufqb-nodejs
  backstage.io/kubernetes-id: h34qtufqb-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h34qtufqb-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml